language: node_js
node_js:
  - 0.10
install:
  - npm install
  - npm install karma-firefox-launcher
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - make test-travis
